config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :lessons
  root to: "lessons#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :title, :time, :teacher, :day_week, :room, :course, :group, presence: true
  scope :lesson_select, -> { select(:id, :title, :time, :teacher, :day_week, :room, :course, :group, :numerator) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  # GET /lessons
  # GET /lessons.json
  def index
    course = params[:course] || 1
    group  = params[:group]  || 1

    render :json => {
        :lessons => Lesson.lesson_select
    }
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :time, :teacher, :room, :day_week, :course, :group, :numerator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Table</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :lesson_title %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :lesson_time %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.text_field :teacher, id: :lesson_teacher %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room, id: :lesson_room %>
  </div>

  <div class="field">
    <%= form.label :day_week %>
    <%= form.text_field :day_week, id: :lesson_day_week %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.number_field :course, id: :lesson_course %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.number_field :group, id: :lesson_group %>
  </div>

  <div class="field">
    <%= form.label :numerator %>
    <%= form.text_field :numerator, id: :lesson_numerator %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th>Teacher</th>
      <th>Room</th>
      <th>Day week</th>
      <th>Course</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.time %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.room %></td>
        <td><%= lesson.day_week %></td>
        <td><%= lesson.course %></td>
        <td><%= lesson.group %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Time:</strong>
  <%= @lesson.time %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @lesson.teacher %>
</p>

<p>
  <strong>Room:</strong>
  <%= @lesson.room %>
</p>

<p>
  <strong>Day week:</strong>
  <%= @lesson.day_week %>
</p>

<p>
  <strong>Course:</strong>
  <%= @lesson.course %>
</p>

<p>
  <strong>Group:</strong>
  <%= @lesson.group %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>